### ISSUE TITLE
Data owners

### ISSUE THREAD

**Issue by trotsiuk** [remoteforests/remoteforests_disturbance#1]
Create a support table for data owners
- [x] Add the table on [vertabello](https://my.vertabelo.com/public-model-view/wumP0SqYbiJfe0vpchD6pGOQ5pBpcZPrds8ocNYZtitoPqYBJAbvsnjJGQVBdqM1?x=2409&y=2358&zoom=0.7530)
    - include the column to the plot table
   - consider last name, first name, email, institute,...
- [x] Create a table in database (PgAdmin)
- [x] Update existing data

**Comment by ondrej-vostarek** [comment]
Hi Vova, 

I have added proposal of the table into the vertabello so please have a look on it and if it is ok I will create it in the database.

Also I have moved the sci table to the parameters_plot, I just want to ask you, if you can send me some info about this parameter so I can add it into the methodology. 

Thank you and have a nice day!

**Comment by ondrej-vostarek** [comment]
Hi Vova,

I created the person table in the database and uploaded the data into it. Do you have any information about the ownership of plots we have in the database so I could pair the persons with them?

Thank you and have a nice day!

**Comment by trotsiuk** [comment]
Hi @ondrej-vostarek looks good!. I don't have anything concrete. Ukraine beech is Mine, Czech spruce is Vojta, and then we need to Ask Miro more about it. One option to put everything on him, and only the sites from Slovakia (one you put out) can be addressed to other people. But better would be to interact with Miro first.

**Comment by ondrej-vostarek** [comment]
Hi @trotsiuk , the information of  the ownership is now uploaded in the database in the ownership column of plot table. Also I would like to ask you about some information concerning the data I moved from sci table into the parameters_plot so I can add the description of this parameter into the methodology. 

Thank you!

Ondra

**Comment by trotsiuk** [comment]
Thank you @ondrej-vostarek, here is the link for the structural complexity index ([sci](http://www.worldagroforestry.org/region/sea/publications/download?dl=/journal/JA0541-14.pdf&pubID=3131))
